# Generated by Django 2.2.3 on 2019-07-20 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song1_name', models.CharField(max_length=100)),
                ('song1_description', models.TextField()),
                ('song1_uploaddate', models.DateTimeField(default=datetime.datetime(2019, 7, 20, 18, 59, 31, 211759))),
            ],
        ),
        migrations.DeleteModel(
            name='abcd',
        ),
    ]
