# Generated by Django 2.2.3 on 2019-07-21 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190720_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song1_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song1_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song1_uploaddate',
        ),
        migrations.AddField(
            model_name='song',
            name='song_uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 21, 18, 19, 38, 88488), verbose_name='Uploaded on'),
        ),
    ]
