# Generated by Django 2.2.4 on 2019-08-05 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190721_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 6, 2, 17, 31, 439413), verbose_name='Uploaded on'),
        ),
    ]
